# Generated by Django 5.0.6 on 2024-07-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['room']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['avaible']},
        ),
    ]
