# Generated by Django 5.0.6 on 2024-07-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
